### ISSUE TITLE
How to use PluginCommand attribute?

### ISSUE THREAD

**Issue by zagvga** [northwood-studios/NwPluginAPI#189]
Is it simple form instead ICommand class implementation? How to use it?
I tried to understand how to use it, but it didn't work...

If something wrong: This is my first issue on GitHub :D

**Comment by moddedmcplayer** [comment]
Unless there is a template, issues have no specific form. If its a bug report youd probably want to to attach the default stuff, etc.
To your question: considering the fact the template plugin dosent even use the PluginAttribute my guess that its not fully implemented, unless @ced777ric says otherwise.

**Comment by ced777ric** [comment]
It would appear that PluginCommandAttribute is not fully implemented and currently just exists.

So i'd recommend sticking to what the template does for its commands.
