### ISSUE TITLE
Player should have userID, raw userID and userID type

### ISSUE THREAD

**Issue by KarlOfDuty** [northwood-studios/NwPluginAPI#37]
Something like:
UserID: 76561198022373616
UserID type: STEAM
Raw userID: 76561198022373616@steam

**Comment by KarlOfDuty** [comment]
As I can't test it right now I can't see what it actually does in the current implementation but there is only one userID variable as far as I can tell.

**Comment by zabszk** [comment]
The game server only operates on "raw UserIDs", so there isn't such function in the API, because that feature and these terms (type, raw) doesn't exit in the server.

I'm not sure whether we need a special method that basically splits a string by `@` and returns two strings.

**Comment by KarlOfDuty** [comment]
Perhaps, I think its pretty common to only use the ID without the type in messages to users though. That's what I was going to use it for.

It's not very important as you can create those variables from the existing userid string so it depends on if you want to include helper functions in the API or not really.

**Comment by moddedmcplayer** [comment]
99% of the time you will still want to differentiate between 1234@steam and 1234@discord.
I can see this being one of the biggest things that will confuse people learning, and if you really, really want it, you can always add it yourself/pr ex. Player.cs: 
Enum.AuthProvider GetAuthProvidor() = ```UserId.Substring(UserId.GetIndexOf('@'), UserId.Lenght-1) switch
{
   "@steam" => Enum.AuthProvider.Steam;
}```

Ofc you would still need a Enum with the auth providers (steam, discord, northwood, and @server apparently since that's the Id of the server)

**Comment by KarlOfDuty** [comment]
Yep indeed, it was just in case you wanted to include the helper functions in the api as they are pretty generic.

**Comment by moddedmcplayer** [comment]
PR it (no balls?)

**Comment by moddedmcplayer** [comment]
Enums are after all just ints with extra text. It is common practice to add a default case to a switch statement, which is realistically the only way im going to see people using it. If you wanna make sure ig you can keep it as string and have a static AuthProvider class with const fields so you can atleast still emulate enum behavoir.

**Comment by zabszk** [comment]
> Enums are after all just ints (by default) with extra text. It is common practice to add a default case to a switch statement, which is realistically the only way im going to see people using it.

That still may lead it issues. Let's say you have 2 users: `123@newProvider1` and `123@newProvider2`.

For `123@newProvider1` you set UserID to `123` and auth provider to `other`. For "raw UserID" `123@newProvider2` you set UserID to `123` and auth provider `other`. Can you see the issue? If you compare users by doing `user1.UserID == user2.UserID && user1.provider == user2.provider` these two users would be considered as the same user, while in fact these are different accounts and different people.

That's why enums (even with default cases) are not a good idea, it may lead to such issues. Even if we return "raw UserIDs" using the API, some programmers may still compare it in the way I describer above.

If you really want to split the ID, then you can split it into 2 strings, however in the great majority of the cases you don't need to split ID into the "user ID without provider" and provider. Usually it's used just as a one string.

**Comment by moddedmcplayer** [comment]
I'm pretty sure you misunderstood my stance, I am totally happy with UserID containing the provider, its just an extra method to get the provider enum, from the UserID field (which contains the provider), as a middle ground. 
I agree with having a field that doesn't contain a provider would be unnecessary and would just cause confusion.
