### ISSUE TITLE
Add PlayerSetNickname event

### ISSUE THREAD

**Issue by KarlOfDuty** [northwood-studios/NwPluginAPI#43]
- Player player
- string oldName

**Comment by zabszk** [comment]
I'm not sure if that event is needed.

First of all nickname can only be set once. It's not possible to change the nickname of the player during the round. And even if someone forces the server to do so, the change will be rejected by all the clients anyway. So there is no need for `oldName` parameter, because it would be always null.

Furthermore in Online Mode nickname is always set almost directly before calling `PlayerJoined` event.

So that event would only make sense in Offline Mode, am I right?

**Comment by KarlOfDuty** [comment]
I guess, the one who requested it only runs offline servers iirc.

**Comment by zabszk** [comment]
> I guess, the one who requested it only runs offline servers iirc.

Currently offline mode is quite broken and that still makes the `oldName` redundant. Generally after 12.0.0 release we will do auth system rework, it will fix offline mode, rework the permissions system (it will be easily usable by plugins then), badges system, etc... after that rework `PlayerJoined` will be called after nickname is set in offline mode as well.

For now we may add such event, however it will get deprecated really soon.

**Comment by KarlOfDuty** [comment]
Merged into #57
