### ISSUE TITLE
Allow viewing cancelled events

### ISSUE THREAD

**Issue by PintTheDragon** [northwood-studios/NwPluginAPI#53]
I think cancelled events should be viewable by plugins. They should also be able to un-cancel events.

Making events fully cancellable by plugins can lead to some issues. I think a good example is the difference between cancelling and handling.

Say, for example, we have a command system that works by having an `CommandExecuted` event. It's been established that this is only for handling commands. In this case, the expectation is that the plugins send some response. Furthermore, they shouldn't send duplicate responses. One way of doing this might be with a `Handled` property somewhere. As soon as one of the plugins handles the command (and so `Handled` is `true`), there's no reason to continue, because it's already been handled.

But this isn't how plugin events work.

Consider the case of a similar event, `CommandRan`. I'm giving them different names, but they're effectively the same. The difference is that `CommandRan` isn't meant for executing commands. Rather, it's meant for letting the plugins do something, anything, when a command is ran. It might also have a `Cancelled` property. If we handle this cancellation the same as handle above, then one plugin may use the event to create a command. When they see the command, they send a response and cancel the event. That's all well and good, but what happens if another plugin comes in and wants to log every command that's ran. Because the previous plugin cancelled, this plugin just won't see the event, and will log incorrectly.

I think the solution to this is to allow plugins to view if an event is cancelled, and maybe also uncancel it. In this case, our first plugin can respond to the user and set it to cancelled. Then, our second plugin will see the event (and that it was cancelled), but will still be able to log it. If any other plugins comes in and tries to respond to the user after the first plugin already did, it can check if the event was cancelled, and if so, not do anything.

*Side note: Plugins should use the actual command system. This is just an example. Also, plugin/event priority would help fix this, but maybe the logging plugin wants to always run last (maybe to see if the event was marked as cancelled).*

**Comment by zabszk** [comment]
> I think cancelled events should be viewable by plugins.

All plugins see all events, even if the event has been cancelled by another plugin before.

> They should also be able to un-cancel events.

That's not a good idea. That can cause issues and bugs. Plugin doesn't know what other plugin cancelled an event and why it was cancelled, so doesn't know whether the event can be safely cancelled. And the plugin that cancelled the event in that case can't be sure if it has been really cancelled.

Imagine a situation - you have a moderation plugin that both handles bans and tracks playtime of players. A banned player attempts to join a server, plugin cancels the event. The next plugin for whatever reason uncancels the event. What's the result:
1. A banned player is playing on the server, because the plugin that uncanceled the event didn't know that the event was canceled, because of a ban.
2. Playtime is probably not even tracked, because the tracking plugin didn't start the timer, because it assumed the player is not on the server (event has been cancelled, right?).

Being able to uncancel events leads to potential issues, bugs and plugin interference. Not mentioning that order of execution matters - in the situation above if you rename the moderation plugin to be loaded after the other plugin, the order of execution of the events would be different, so the first plugin wouldn't know that the event is cancelled and the cancellation of the moderation plugin wouldn't be cancelled.

The information about event cancellation is not useful - the fact that the event isn't cancelled right now, doesn't mean that it won't be cancelled by the next plugin. Why would you even need such information?

And at the end, some programmers (especially new to SCP:SL plugin framework) might not know the difference between `if (condition) SetCancelled(true);` and `SetCancelled(!condition);` and accidentally uncancel cancellations of plugins that cancelled the event before.

The example with commands is not really good, because such system exists - we have the command run event and the command system (that actually lets only one plugin to handle it).

So you suggest to duplicate every event and first run "Copy A" and if none of the plugins cancel it then run "Copy B"? Events are not usually handled by plugins, but by the base game. It's not common for example for a plugin to handle interaction with doors. And even if you have some custom game mode plugin that entirely reworks door interactions, then you have only one plugin like that. You don't have two plugins that rework door interaction, they would interfere with each other.

> Also, plugin/event priority would help fix this

Event priority would change the situation described above. When it comes to event priority, it makes sense to add a bool informing whether the event has been cancelled by a plugin with higher priority. Or maybe even add a bool/attribute describing whether the plugin even wants to have a specific event called, if it's already cancelled by a plugin with a higher priority.

**Comment by PintTheDragon** [comment]
I'm sorry, I've completely misinterpreted the meaning of
```csharp
if (cancelled || result is null)
     continue;
```

My main argument was for allowing plugins to view cancelled events, and as it's already a feature, I'll be closing this issue. 

My example above is just there for the sake of argument. You could come up with many other examples (maybe plugin A wants to disallow drops and plugin B wants to log user interactions), but I think that example is just more intuitive and conveys the actual issue better. And yeah, priorities would be very useful for plugins that want to know if the event was cancelled.

I still think un-cancelling events is worthwhile in some cases, but I agree that preventing it is probably a good idea in the vast majority of cases. Maybe adding a way to allow the plugin to explicitly un-cancel the event (something like `return UnsafeSetCancelled(false);`) would be a good way to handle it.
