### ISSUE TITLE
Wrong arguments in PlayerInteractLocker

### ISSUE THREAD

**Issue by Bujapetas** [northwood-studios/NwPluginAPI#76]
```cs
[2022-12-15 00:48:45.131 +00:00] [Error] [PluginAPI] Event OnInteractWithLocker (PlayerInteractLocker) in plugin MyPlugin.Plugin contains wrong parameters
                                  - Player, Locker, Byte, Boolean
                                  - Required:
                                  - IPlayer.
```

I used the github template and only changed MyPlayer to Player.

**Comment by MrAfitol** [comment]
The same thing

**Comment by zabszk** [comment]
Are you sure that the server and the plugin use the same version of NwPluginAPI? You can check the API version used by the server by going to the server directory, then `SCPSL_Data/Managed/`, then right click `PluginAPI.dll`, select `Properties`, go to the `Details` tab and check `Product version`.

This repository is often ahead of the currently released SCP:SL Dedicated Server build. If you need to get a specific NwPluginAPI version you should view a specific tag instead of the master branch.

**Comment by Bujapetas** [comment]
Was fixed with the last version
